version: "3.4"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - application-network
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana-provisioning/dashboards:/var/lib/grafana/dashboards
    environment: 
      GF_SERVER_PROTOCOL: http
      GF_SERVER_HTTP_PORT: 3000
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_ANONYMOUS_ENABLED: 1
      GF_AUTH_BASIC_ENABLED: 0
      GF_SERVER_SERVE_FROM_SUB_PATH: 1      
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - 8086:8086
      - 8083:8083
    networks: 
      - application-network
    environment: 
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_BIND_ADDRESS: ":8083"
      INFLUXDB_ADMIN_USER_TOKEN: "admin"
      INFLUXDB_ADMIN_USER_PASSWORD: "01d58074-d469-4645-9985-58c37b4b7ab7"
  k6:
    image: loadimpact/k6:latest
    container_name: k6
    networks: 
      - application-network
    volumes: 
      - ./src:/src/scripts
    command: run --out influxdb=http://influxdb:8086/myk6db /src/scripts/boleto-emit.spike-test.js
    
networks:
  application-network:
    driver: bridge